language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
scala:
   - 2.11.6
apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - gcc
      - binutils
      - python-pip
r_packages:
  - Imap
before_install:
  - pip install --user codecov
after_success:
# For now no coverage report
  - codecov