version: '{build}'

platform:
  - x86
  - x64

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0


install:
- ps: Start-FileDownload 'http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.9/sbt-launch.jar'
- xcopy sbt-launch.jar sbt\
- set PATH=C:\msys64\usr\bin;%PATH%
- set MSYSTEM=MINGW64
- bash -lc ""
- bash -lc "pacman --noconfirm --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel"
..
- bash -lc "pacman --noconfirm -S mingw-w64-x86_64-{gcc,gcc-ada,gcc-fortran,gcc-libgfortran,gcc-objc,cmake,make,icu,jemalloc,zlib}"
before_build:
- set MSYSTEM=MINGW64

build_script:
- set MSYSTEM=MINGW64
- bash -lc "export PATH=/mingw64/bin:$PATH && ./sbt/sbt clean compile"

test_script:
- bash -lc "export PATH=/mingw64/bin:$PATH && ./sbt/sbt \"testOnly com.highperformancespark.examples.tools.*\""

cache:
- C:\Users\appveyor\.ivy2
- C:\Users\appveyor\.m2
- C:\Users\appveyor\.sbt